Hmm

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -108,6 +108,16 @@ jobs:
   test-bun:
     name: Unit Test on Bun
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest] # remove windows to speed up the tests
+        graphql_version:
+          - 15
+          - 16
+        include:
+          - os: windows-latest
+            graphql_version: 16
     steps:
       - name: Checkout Master
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
@@ -117,6 +127,10 @@ jobs:
         with:
           nodeVersion: 23
 
+      - name: Use GraphQL v${{matrix.graphql_version}}
+        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
+      - name: Install Dependencies using Yarn
+        run: yarn install --ignore-engines && git checkout yarn.lock
       - name: Build
         run: yarn build
       - name: Unit Tests
@@ -124,4 +138,9 @@ jobs:
         with:
           timeout_minutes: 10
           max_attempts: 5
-          command: yarn test:bun --ci
+          command: yarn test:bun --ci --reporter=junit --reporter-outfile=./junit.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './junit.xml'
