Run tests with Bun (#6863)
* Run tests with Bun

* Hmm

* Fix tests

* Hmm

* Fix Unit tests

* Clear lest

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -94,10 +94,50 @@ jobs:
       - name: Build
         run: yarn build
       - name: Unit Tests
-        run: yarn test --ci
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          command: yarn test --ci
       - name: Leak Tests
         uses: nick-fields/retry@v3
         with:
           timeout_minutes: 10
           max_attempts: 5
           command: yarn test:leaks --ci
+  test-bun:
+    name: Unit Test on Bun (${{matrix.os}}) and GraphQL v${{matrix.graphql_version}}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest] # remove windows to speed up the tests
+        graphql_version:
+          - 15
+          - 16
+    steps:
+      - name: Checkout Master
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+
+      - name: Setup env
+        uses: the-guild-org/shared-config/setup@main
+        with:
+          nodeVersion: 23
+
+      - name: Use GraphQL v${{matrix.graphql_version}}
+        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
+      - name: Install Dependencies using Yarn
+        run: yarn install --ignore-engines && git checkout yarn.lock
+      - name: Build
+        run: yarn build
+      - name: Unit Tests
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          command: yarn test:bun --ci --reporter=junit --reporter-outfile=./junit.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './junit.xml'
